language: python

python:
  - "2.7"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev

install:
  - pip install codeclimate-test-reporter

script:
  - coverage run test.py

after_success:
  - codeclimate-test-reporter

addons:
    code_climate:
        repo_token: cefb790632e41dfd61e92750add14cd9797b932186d47dcb29ee0e682d4df2d7 
