# https://ci.appveyor.com/project/mikusjelly/magic
build: false

branches:
  only:
    - master

environment:
  matrix:
    - PYTHON: "C:/Python35"

init:
  - "ECHO %PYTHON%"
  - ps: "ls C:/Python*"

install:

test_script:
  - "%PYTHON%/python.exe test.py"
